name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/60 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Zhaodaidai
        uses: 952971812@qq.com

      - name: Auto green
        run: |
          git config --local user.email "justjavac@gmail.com"
          git config --local user.name "迷渡"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
